# 项目相关配置
# 开发环境配置
# oss微服务 用户接入第三方文件系统
server:
  # 服务器的HTTP端口，默认为9082
  port: 9082
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
#logging:
#  level:
#    com.lq: debug
#    org.springframework: warn

# Spring配置
spring:
  profiles:
    active: dev
aliyun:
  oss:
    ak: LTAI5t6zQ3TSfNW6DgmNVH9L
    sk: OJjkCekjNg5a1iniwnjkQGllVUL5oj
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: sub-lq
